# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.TextField(default=False),
        ),
    ]
