# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160831_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='Add ingredients here.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(default='Add product here.', primary_key=True, serialize=False),
        ),
    ]
