# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160831_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', help_text='Add an image for the product.', upload_to=''),
            preserve_default=False,
        ),
    ]
