# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(help_text='Add ingredients here.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(help_text='Add product here.', primary_key=True, serialize=False),
        ),
    ]
